name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
    - name: run script
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.getRef({
            owner: 'srh-sloan',
            repo: 'actions-in-action',
            ref: 'tags/1.0',
          });
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"

