name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(context)

