name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Script
        uses: actions/github-script@v6.1.0
        with:
          debug: True
          # The script to run
          script: echo hello world

