name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run script
        run: echo in script

      - name: get tags
        uses: actions/github-script@v6
        with:
          script: |
            echo running script in github-script step


