name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
    - name: Check if tag exists
    - uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      with: 
        tag: 'v1'
 #     env:
 #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo ${{ steps.checkTag.outputs.exists }}

