name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: echo copied this

