name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v3
    

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Get package version
      id: package_version
      run: echo "::set-output name=python_version::"$(python setup.py --version)

    - uses: ncipollo/release-action@v1
      name: create release
      id: create_release
      with:
        commit: tagging
        tag: ${{ steps.package_version.outputs.python }}
        token: ${{ secrets.GITHUB_TOKEN }}
 
