name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Get package version
      id: package_version
      run: echo "::set-output name=app_version::"$(python setup.py --version)
    - name: print package version
      id: print_version
      run: echo ${{ steps.package_version.outputs.app_version}}

    - uses: ncipollo/release-action@v1
      name: create release
      id: create_release
      with:
        commit: main
        tag: ${{ steps.package_version.outputs.app_version }}
        token: ${{ secrets.GITHUB_TOKEN }}
 
