name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
    - name: run script
      uses: actions/github-script@v6
      with:
        script: |
          console.log('hello world')
          consolge.log('another line')

