name: tagging

on: 
  workflow_dispatch:
  push:
    branches: [ "tagging" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      name: create release
      id: create_release
      with:
        commit: tagging
        tag: v2
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: check release created
      run: |
        echo Output: ${{ steps.create_release.outputs }}


  tag-exists:
    runs-on: ubuntu-latest
    steps:
    - name: Check if tag exists
      uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      with: 
        tag: 'v2'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo ${{ steps.checkTag.outputs.exists }}
 
